In [6]:
import sys
sys.path.append("..")

from dataset.utils import get_cached_data

In [7]:
x, y = get_cached_data("../artifacts")

In [3]:
x.shape

(5000, 500)

In [13]:
import numpy as np

corr_matrix = np.corrcoef(x, rowvar=False)

In [10]:
corr_matrix.shape

(500, 500)

In [11]:
corr_matrix

array([[ 1.00000000e+00,  8.55214083e-01,  7.63481766e-01, ...,
         2.90037436e-03, -1.68930235e-02,  6.84343388e-04],
       [ 8.55214083e-01,  1.00000000e+00,  7.68779586e-01, ...,
        -9.08206626e-03, -1.89422444e-02, -6.22810977e-03],
       [ 7.63481766e-01,  7.68779586e-01,  1.00000000e+00, ...,
         8.95916482e-05, -1.20801339e-02, -2.45980004e-03],
       ...,
       [ 2.90037436e-03, -9.08206626e-03,  8.95916482e-05, ...,
         1.00000000e+00,  8.46094807e-03, -1.51651868e-02],
       [-1.68930235e-02, -1.89422444e-02, -1.20801339e-02, ...,
         8.46094807e-03,  1.00000000e+00, -5.98345020e-03],
       [ 6.84343388e-04, -6.22810977e-03, -2.45980004e-03, ...,
        -1.51651868e-02, -5.98345020e-03,  1.00000000e+00]])

In [12]:
threshold = 0.75
correlated_pairs = np.where(np.abs(corr_matrix) > threshold)
correlated_pairs = [(i, j) for i, j in zip(*correlated_pairs) if i != j and i < j]

In [14]:
features_to_remove = set()
    
for _, j in correlated_pairs:
    features_to_remove.add(j)
    
features_to_remove = list(features_to_remove)
features_to_remove

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
np.mean(x[:, 105]), np.std(x[:, 105])

(-0.0058915863645113715, 1.0010853571630096)

In [10]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(x[:, [0]+list(range(10, 500))], y)
mdi_importances = clf.feature_importances_
mdi_importances

array([0.00506913, 0.00157469, 0.0018185 , 0.00184401, 0.00158879,
       0.00168844, 0.00194283, 0.00184904, 0.00204971, 0.00228051,
       0.00198342, 0.00248235, 0.00190347, 0.00171907, 0.00174795,
       0.0020921 , 0.00193895, 0.0015413 , 0.00232409, 0.00231197,
       0.00230522, 0.00222736, 0.00161194, 0.00198775, 0.00167709,
       0.00231126, 0.00206389, 0.00195549, 0.00185636, 0.00197975,
       0.0019509 , 0.0017019 , 0.00158862, 0.00214193, 0.00185287,
       0.00158456, 0.0020212 , 0.00205561, 0.00152266, 0.00170023,
       0.00153007, 0.00182809, 0.00179336, 0.00215265, 0.00189566,
       0.00202465, 0.00158059, 0.0019781 , 0.00190876, 0.00219727,
       0.00229036, 0.00196001, 0.00157776, 0.00189816, 0.00189121,
       0.00220183, 0.00209292, 0.00190208, 0.00178113, 0.0020771 ,
       0.00163383, 0.00242599, 0.00218662, 0.00253494, 0.00168952,
       0.00205786, 0.00217326, 0.00178232, 0.00194642, 0.00217256,
       0.00170358, 0.00219307, 0.00183809, 0.00154031, 0.00200

In [25]:
features = np.argsort(mdi_importances)[::-1]+9
features

array([105, 102, 100, 103, 101, 104,   9, 498, 319, 129, 144,  72, 328,
       212, 355, 323,  20, 360, 266, 420,  70, 424, 121,  88, 118, 200,
       329, 202, 284, 447, 142,  27, 303,  28,  34, 363,  29, 403, 213,
       235, 302, 488,  59, 316, 307, 314, 471, 448, 171, 321, 462,  18,
       252, 412, 253, 207, 362, 277, 246, 237, 389,  30, 226, 288, 464,
       394, 422, 458, 115, 113,  94, 346,  64, 459, 270,  99,  58, 285,
        80, 184, 143,  71, 283, 249, 276, 398, 324,  75,  78, 371, 497,
       211, 151, 112, 208, 491, 139, 331,  52, 306,  95,  42, 400, 107,
       481, 162, 428, 196, 175, 357, 227, 268, 218, 373, 225, 247, 131,
       335, 190, 460, 345, 146, 221, 178, 442, 203, 209, 416,  65, 409,
        24, 296, 295, 467, 450, 159,  68, 337, 443, 395, 344,  98, 161,
       158, 122, 215,  35, 479, 258, 130, 451, 406,  74, 343,  46, 327,
       484, 156, 164,  17, 472, 228, 330, 499, 432, 219, 322, 463, 132,
       423, 454, 193, 256, 152, 426, 386, 376, 138, 435, 427, 33

In [27]:
for i in range(10):
    print("Feature", features[i], "importance:", mdi_importances[features[i]-9])

Feature 105 importance: 0.010535882733552297
Feature 102 importance: 0.009977198456265985
Feature 100 importance: 0.009363263769753792
Feature 103 importance: 0.008601968702856053
Feature 101 importance: 0.007800331860220733
Feature 104 importance: 0.006910008114602371
Feature 9 importance: 0.00506912634110211
Feature 498 importance: 0.00260359609400318
Feature 319 importance: 0.0025896686108965567
Feature 129 importance: 0.0025694432828333373


In [3]:
from itertools import combinations

list(combinations([1, 2, 3], 2))

[(1, 2), (1, 3), (2, 3)]

In [8]:
from metrics import calculate_gain
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis, LinearDiscriminantAnalysis
from sklearn.svm import SVC

def evaluate_models(x_train, x_test, y_train, y_test, selected_features):
    gains = []
    clf = RandomForestClassifier(n_estimators=100, random_state=42)
    clf.fit(x_train, y_train)
    predictions = clf.predict(x_test)
    gains.append(calculate_gain(y_test, predictions, len(selected_features)))
    #print("Random forest:", calculate_gain(y_test, predictions, len(selected_features)))
    
    qda = QuadraticDiscriminantAnalysis()
    qda.fit(x_train, y_train)
    predictions = qda.predict_proba(x_test)[:, 1]
    gains.append(calculate_gain(y_test, predictions, len(selected_features)))
    #print("QDA:", calculate_gain(y_test, predictions, len(selected_features)))
    
    poly = PolynomialFeatures(degree=2, interaction_only=False, include_bias=False)
    x_train_poly = poly.fit_transform(x_train)
    x_test_poly = poly.transform(x_test)
    
    qda = QuadraticDiscriminantAnalysis()
    qda.fit(x_train_poly, y_train)
    predictions = qda.predict_proba(x_test_poly)[:, 1]
    gains.append(calculate_gain(y_test, predictions, len(selected_features)))
    #print("QDA Poly:", calculate_gain(y_test, predictions, len(selected_features)))
    
    lda = LinearDiscriminantAnalysis()
    lda.fit(x_train, y_train)
    predictions = lda.predict_proba(x_test)[:, 1]
    gains.append(calculate_gain(y_test, predictions, len(selected_features)))
    #print("LDA:", calculate_gain(y_test, predictions, len(selected_features)))
    
    svm = SVC(probability=True)
    svm.fit(x_train, y_train)
    predictions = svm.predict_proba(x_test)[:, 1]
    gains.append(calculate_gain(y_test, predictions, len(selected_features)))
    #print("SVM:", calculate_gain(y_test, predictions, len(selected_features)))
    
    return gains

In [11]:
from tqdm import tqdm
selected_features = [0, 100, 101, 102, 103, 104, 105]
comb = list(combinations(selected_features, 1)) + list(combinations(selected_features, 2)) + list(combinations(selected_features, 3)) + list(combinations(selected_features, 4)) + list(combinations(selected_features, 5))
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
data = []
for i in tqdm(comb):
    x_train_selected = x_train[:, i]
    x_test_selected = x_test[:, i]
    data.append(evaluate_models(x_train_selected, x_test_selected, y_train, y_test, i))

100%|██████████| 119/119 [05:30<00:00,  2.78s/it]


In [14]:
data = np.array(data)

In [15]:
np.unravel_index(data.argmax(), data.shape)

(39, 4)

In [16]:
comb[39], data[39, 4]

((0, 102, 105), 7450.000000000001)

In [17]:
import pandas as pd

df = pd.DataFrame(data, columns=["Random Forest", "QDA", "QDA Poly", "LDA", "SVM"])
df.set_index(pd.Series(comb), inplace=True)
df

Random Forest     QDA  QDA Poly     LDA     SVM
(0,)                              5000.0  6150.0    6150.0  5400.0  6250.0
(100,)                            4850.0  7050.0    7050.0  5900.0  7050.0
(101,)                            4900.0  6400.0    6450.0  5600.0  6350.0
(102,)                            4750.0  6300.0    6300.0  5500.0  6300.0
(103,)                            4900.0  6000.0    6050.0  5450.0  5800.0
...                                  ...     ...       ...     ...     ...
(100, 101, 102, 103, 105)         6050.0  7050.0    7100.0  5050.0  7200.0
(100, 101, 102, 104, 105)         5450.0  6950.0    6800.0  5450.0  6750.0
(100, 101, 103, 104, 105)         5650.0  6950.0    6750.0  5150.0  6700.0
(100, 102, 103, 104, 105)         5400.0  6850.0    6700.0  5100.0  7000.0
(101, 102, 103, 104, 105)         5000.0  7250.0    7100.0  5200.0  6900.0

[119 rows x 5 columns]

In [94]:
from xgboost import XGBClassifier

i = (102, 103, 105)
x_train_selected = x_train[:, i]
x_test_selected = x_test[:, i]

xgb = XGBClassifier(
    objective='binary:logistic', 
    n_estimators=1000, 
    learning_rate=0.1, 
    max_depth=15, 
    use_label_encoder=False,
    eval_metric='logloss'
)
xgb.fit(x_train_selected, y_train)
predictions = xgb.predict_proba(x_test_selected)[:, 1]
calculate_gain(y_test, predictions, len(i))

6050.0

In [99]:
poly = PolynomialFeatures(degree=2, interaction_only=True, include_bias=False)
x_train_poly = poly.fit_transform(x_train_selected)
x_test_poly = poly.transform(x_test_selected)

xgb.fit(x_train_poly, y_train)
predictions = xgb.predict_proba(x_test_poly)[:, 1]
calculate_gain(y_test, predictions, len(i))

6400.0

In [101]:
svm = SVC(probability=True, kernel="linear")
svm.fit(x_train_selected, y_train)
predictions = svm.predict_proba(x_test_selected)[:, 1]
calculate_gain(y_test, predictions, len(i))

4200.0

In [62]:
clf2 = RandomForestClassifier(n_estimators=100, random_state=42)

clf2.fit(x_train_selected, y_train)
predictions = clf2.predict(x_test_selected)
calculate_gain(y_test, predictions, len(selected_features))

5200.0

In [63]:
qda = QuadraticDiscriminantAnalysis()
qda.fit(x_train_selected, y_train)
predictions = qda.predict_proba(x_test_selected)[:, 1]
calculate_gain(y_test, predictions, len(selected_features))

7150.0

In [64]:
poly = PolynomialFeatures(degree=2, interaction_only=False, include_bias=False)
x_train_poly = poly.fit_transform(x_train_selected)
x_test_poly = poly.transform(x_test_selected)

qda = QuadraticDiscriminantAnalysis()
qda.fit(x_train_poly, y_train)

predictions = qda.predict_proba(x_test_poly)[:, 1]
calculate_gain(y_test, predictions, len(selected_features))

7200.0

In [66]:
# LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda = LinearDiscriminantAnalysis()
lda.fit(x_train_selected, y_train)
predictions = lda.predict_proba(x_test_selected)[:, 1]
calculate_gain(y_test, predictions, len(selected_features))

5400.0

In [67]:
# SVM
from sklearn.svm import SVC

svm = SVC(probability=True)
svm.fit(x_train_selected, y_train)
predictions = svm.predict_proba(x_test_selected)[:, 1]
calculate_gain(y_test, predictions, len(selected_features))

7000.0

In [61]:
import numpy as np
import pandas as pd
from scipy.interpolate import BSpline
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import SplineTransformer
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

i = (102, 103, 105)
x_train_selected = x_train[:, i]
x_test_selected = x_test[:, i]

spline_transformer = SplineTransformer(n_knots=2, degree=3)

# Fit and transform the training data
X_train_spline = spline_transformer.fit_transform(x_train_selected)
X_test_spline = spline_transformer.transform(x_test_selected)
model = LinearDiscriminantAnalysis()
model.fit(X_train_spline, y_train)
predictions = model.predict_proba(X_test_spline)[:, 1]
calculate_gain(y_test, predictions, len(i))

7100.0

In [56]:
poly = PolynomialFeatures(degree=3, interaction_only=False, include_bias=False)
x_train_poly = poly.fit_transform(x_train_selected)
x_test_poly = poly.transform(x_test_selected)

qda = LinearDiscriminantAnalysis()
qda.fit(x_train_poly, y_train)
predictions = qda.predict_proba(x_test_poly)[:, 1]
calculate_gain(y_test, predictions, len(i))

7450.000000000001